### PR TITLE
Standardize internal compiler error messages

### LINKED ISSUE #76: Standardize errors that are the programs fault
We would like a standard utility function or a consistent policy for raising errors that we expect to never be hit. They should ideally serialize a relevant data structure in the error message. A simple version of this could be something like:

```
let fatal_error (data_structure : 'a) =
  prerr_endline ("Fatal error: this should never happen. Please file a bug on https://github.com/stan-dev/stanc3/issues/new. Offending data structure:") ;
  raise_s [%sexp (data_structure : 'a)]
```

### PR DESCRIPTION
**Pull request by WardBrian**
This closes #76 

It adds `Common.FatalError.fatal_error_msg`, which is a drop-in replacement for `raise_s` that prepends the following message:
`Fatal error: this should never happen. Please file a bug on https://github.com/stan-dev/stanc3/issues/new.`

and `Common.FatalError.fatal_error` which is the same as the above but doesn't take in any additional message/sexp.

We previously had a Frontend.Errors.fatal_error, but it wasn't used, and it felt like it should live in Common (rather than importing the frontend into the code generator, for example).

I also updated all existing calls to either `raise_s` or `failwith` in the compiler.

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [x] OR, no user-facing changes were made

## Release notes

All internal compiler errors now include a link to the stanc3 issues page.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: src/analysis_and_optimization/Mir_utils.ml [hunk 1]
```diff
@@ -241,7 +241,9 @@ let fwd_traverse_statement stmt ~init ~f =
 let vexpr_of_expr_exn Expr.Fixed.({pattern; _}) =
   match pattern with
   | Var s -> VVar s
-  | _ -> raise (Failure "Non-var expression found, but var expected")
+  | _ ->
+      Common.FatalError.fatal_error_msg
+        [%message "FNon-var expression found, but var expected"]
```
Comment (mcol) [inline src/analysis_and_optimization/Mir_utils.ml:246]: Typo `FNon-var`?

File: src/stan_math_backend/Stan_math_code_gen.ml [hunk 2]
```diff
@@ -294,9 +294,12 @@ let pp_fun_def ppf Program.({fdrt; fdname; fdsuffix; fdargs; fdbody; _})
...
               ([slice; start ^ " + 1"; end_ ^ " + 1"], rest, `ReduceSum)
         | _ ->
-            raise_s
+            Common.FatalError.fatal_error_msg
               [%message
-                "Ill-formed reduce_sum call! This is bug in the compiler."]
+                "Ill-formed reduce_sum call!"
+                  ( fdargs
+                    : (UnsizedType.autodifftype * string * UnsizedType.t) list
+                    )]
```
Comment (nhuurre) [inline src/stan_math_backend/Stan_math_code_gen.ml:302]:
```suggestion
                "Ill-formed reduce_sum call!" (fdargs : Program.fun_arg_decl)]
```

File: src/frontend/dune [hunk 3]
```diff
@@ -1,47 +1,54 @@
...
+     parser.messages))))
 
 (menhir
  (modules parser)
  (flags :standard --table --strict --unused-tokens --fixed-exception))
 
 (rule
- (with-stdout-to parser_updated.messages
+ (with-stdout-to
+  parser_updated.messages
```
Comment (nhuurre) [inline src/frontend/dune:27]: What's the reason for these spacing changes? `run menhir` above collects the options to the same line but here the line is split into two.

File: src/analysis_and_optimization/Partial_evaluator.ml [hunk 4]
```diff
@@ -22,7 +22,7 @@ let apply_prefix_operator_int (op : string) i =
         | "PPlus__" -> i
         | "PMinus__" -> -i
         | "PNot__" -> if i = 0 then 1 else 0
-        | s -> raise_s [%sexp (s : string)] ) )
+        | s -> Common.FatalError.fatal_error_msg [%message s] ) )
```
Comment (nhuurre) [inline src/analysis_and_optimization/Partial_evaluator.ml:25]: A stupid question from someone who knows nothing about Sexplib: what's the difference between `[%sexp ...]` and `[%message ...]`? `Optimize.ml` has one fatal error that keeps `[%sexp ...]` but here in `Partial_evaluator.ml` they're all changed to `[%message ...]`.

File: src/frontend/dune (hunk 3 above)
Comment (WardBrian) [reply src/frontend/dune:27]: I think I ran ocamlformat on this file by accident, will revert

File: src/analysis_and_optimization/Partial_evaluator.ml (hunk 4 above)
Comment (WardBrian) [reply src/analysis_and_optimization/Partial_evaluator.ml:25]: The difference is subtle and honestly seems kind of arbitrary. `[%message` comes from https://github.com/janestreet/ppx_sexp_message, and `[%sexp` comes from https://github.com/janestreet/ppx_sexp_value

They have slightly different behavior for how they label their values, which is relevant for when the payload is only a string. `[%sexp (s:string)]` will output something like `(s ("The contents of the string"))`, while `[%message s]` should just output `The contents of the string`, but they accomplish the same goal in the end

**Review by nhuurre — APPROVED** [review]
Looks good to me.
