### PR TITLE
Don't try to inline StanLib fun calls, ever

### LINKED ISSUE #1473: [BUG] Function inlining breaks with complicated tilde overloads
After #1466, the compiler can now resolve these during typechecking, but the wrong thing can still be done during inlining. 

For example:

`stanc --O1 test/integration/good/code-gen/overload_tilde_stanlib.stan `

yields

```
Internal compiler error:
(Invalid_argument "length mismatch in zip_exn: 3 <> 2")
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Analysis_and_optimization__Optimize.subst_args_stmt in file "src/analysis_and_optimization/Optimize.ml", line 114, characters 32-54
Called from Analysis_and_optimization__Optimize.inline_function_expression in file "src/analysis_and_optimization/Optimize.ml", line 307, characters 22-110
Called from Analysis_and_optimization__Optimize.inline_function_statement in file "src/analysis_and_optimization/Optimize.ml", line 397, characters 26-69
Called from Base__List.count_map in file "src/list.ml", line 479, characters 13-17
Called from Base__List.map in file "src/list.ml" (inlined), line 510, characters 15-31
Called from Analysis_and_optimization__Optimize.inline_function_statement in file "src/analysis_and_optimization/Optimize.ml", line 469, characters 18-76
Called from Base__List.count_map in file "src/list.ml", line 483, characters 13-17
Called from Base__List.map in file "src/list.ml" (inlined), line 510, characters 15-31
Called from Analysis_and_optimization__Optimize.function_inlining in file "src/analysis_and_optimization/Optimize.ml" (inlined), line 528, characters 4-119
Called from Analysis_and_optimization__Optimize.function_inlining in file "src/analysis_and_optimization/Optimize.ml", line 538, characters 6-71
Called from Base__List0.fold in file "src/list0.ml", line 37, characters 27-37
Called from Dune__exe__Stanc.use_file in file "src/stanc/stanc.ml", line 361, characters 6-61
Called from Common__ICE.with_exn_message in file "src/common/ICE.ml", line 14, characters 9-15
```

Considering the compiler never properly compiled these before, this doesn't strike me as hold-the-release worthy, but would be nice to fix

### PR DESCRIPTION
**Pull request by WardBrian**
Closes #1473. As far as I can tell, this code was always wrong, but relied on the map lookup failing for StanLib functions. How this got missed during the function overloading PRs I'm not sure.

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Fixed a internal compiler error in the function inlining optimization

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by SteveBronder — APPROVED** [review]

File: src/analysis_and_optimization/Optimize.ml [hunk 1]
```diff
@@ -249,6 +249,19 @@ let inline_list f es =
   let es = List.map ~f:(function _, _, x -> x) dse_list in
   (d_list, s_list, es)
 
+let compute_suffix_and_name propto suffix fname =
+  let open Fun_kind in
+  match suffix with
+  | FnLpdf propto' when propto' && propto ->
+      ( FnLpdf true
+      , with_unnormalized_suffix fname |> Option.value ~default:fname )
```
Comment (nhuurre) [inline src/analysis_and_optimization/Optimize.ml:257]: Why do we need the unnormalized function name here? When this is removed, test output changes but only for stanlib functions which makes no sense to me.

Comment (WardBrian) [reply src/analysis_and_optimization/Optimize.ml:257]: In `create_function_inline_map` there is some special logic that adds both the normalized and unnormalized function names to the map, with the only difference being the value of `propto` for the call to `inline_function_statement` on the body.

So, I believe this impacts when a pdf is inlined into another pdf, do we treat it as if it was a updf or not. The changes are impacting stdlib function calls because the tests contain udfs which are defined in terms of stdlibs, which can't be themselves inlined further
