### PR TITLE
Properly handle nested container expression promotion

### LINKED ISSUE #1291: [BUG] Inline matrix construction fails to promote with mixed types
The following model fails to compile:
```stan

data {
  real y_mean;
}

parameters {
  real y;
}

transformed parameters {
  matrix[2, 2] M;
  M = [[1, 2], [3, y]];
}

model {
  y ~ normal(y_mean, 1);
}
```

With the error:
```
/Users/andrew/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/functors/AssignmentFunctors.h:24:104: error: assigning to 'double' from incompatible type 'const stan::math::var_value<double>'
```

Because the construction of `M` is transpiling to:
```cpp
      stan::model::assign(M, stan::math::to_matrix(
        std::vector<Eigen::Matrix<double, 1, -1>>{
        (Eigen::Matrix<double,1,-1>(2) << 1, 2).finished(),
        (Eigen::Matrix<local_scalar_t__,1,-1>(2) << 3, y).finished()}),
        "assigning variable M");
```

Where the `std::vector<Eigen::Matrix<double, 1, -1>>` should more likely be `std::vector<Eigen::Matrix<local_scalar_t__, 1, -1>>`

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Closes #1291. Fixes an issue where the compiler would generate uncompilable C++ when a matrix expression featured mixed types of elements. 

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

File: src/frontend/Promotion.ml [hunk 1]
```diff
@@ -61,7 +64,9 @@ let rec promote (exp : Ast.typed_expression) prom =
   | RowVectorExpr (_ :: _ as es) ->
       let pes = List.map ~f:(fun e -> promote e prom) es in
       let fst = List.hd_exn pes in
-      let ad_level = fst.emeta.ad_level in
+      let ad_level =
```
Comment (WardBrian) [inline src/frontend/Promotion.ml:67]: This is the change that fixed the bug; the rest are just cleanups. I’m not sure why arrays previously seemed to work just fine while matrices didn’t, I couldn’t find where in the code they diverged in behavior.

Comment (nhuurre) [reply src/frontend/Promotion.ml:67]: Arrays were broken too if the inner type is a row vector.
```stan
array[2] row_vector[2] Mar;
Mar = {[1, 2], [3, y]};
```

**Review by nhuurre — APPROVED** [review]
